#define VERSION "@CMOD_VERSION@"

#define SYSTEM_TYPE "@CMOD_SYSTEM@"

#define MACHINE_TYPE "@CMOD_MACHINE_TYPE@"

#define PACKAGE_STRING "Cmod @CMOD_VERSION@"

#define PACKAGE_BUGREPORT "@CMOD_BUG_REPORT@"

#cmakedefine HAVE_STRLEN "@CMOD_HAVE_STRLEN@"

#cmakedefine HAVE_STRDUP "@CMOD_HAVE_STRDUP@"

#cmakedefine CRAPLE @CMOD_CRAPLE@

#cmakedefine DEBUG @C_DEBUG@

#cmakedefine HAVE_STDIO_H @HAVE_STDIO@

#cmakedefine HAVE_STDLIB_H @HAVE_STDLIB@

#cmakedefine HAVE_STDBOOL_H @HAVE_BOOL@

#cmakedefine HAVE_STRING_H @HAVE_STRING@